resolution:
  "720 x 1280"
back:
  "adb shell input keyevent 4"
power:
  "adb shell input keyevent 26"
home:
  "adb shell input keyevent 3"
close:
  "adb shell am force-stop com.alibaba.android.rimet"
open:
  "adb shell monkey -p com.alibaba.android.rimet -c android.intent.category.LAUNCHER 1"
manager:
  "adb shell input tap 349 1123"
getin:
  "adb shell input tap 108 687"
card:
  "adb shell input tap 366 659"
screenshot:
  "adb shell screencap -p /sdcard/autocard.png"
download:
  "adb pull /sdcard/autocard.png ."
delete:
  "adb shell rm -r /sdcard/autocard.png"
steps:
  - "adb shell input keyevent 3"
  - "adb shell am force-stop com.alibaba.android.rimet"
  - "adb shell monkey -p com.alibaba.android.rimet -c android.intent.category.LAUNCHER 1"
  - "adb shell input tap 349 1123"
  - "adb shell input tap 108 687"
  - "adb shell input tap 366 659"
  - "adb shell screencap -p /sdcard/autocard.png"
  - "adb pull /sdcard/autocard.png ."
  - "adb shell rm -r /sdcard/autocard.png"
reciver:
  "********@**.**"
sender:
  account: "*********@**.**"
  psw: "***********"
adbpath:
  ""